name: GitHub CI

on:
  pull_request:
  push:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * 0

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:

  generate-jobs:
    name: Generate Jobs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["1.21", "1.22"] 
        variant: ["sid", "alpineedge"]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.version }}/${{ matrix.variant }}
          platforms: linux/riscv64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/golang:${{ matrix.version }}-${{ matrix.variant }}
            ghcr.io/${{ github.repository_owner }}/golang:${{ matrix.version }}${{ matrix.variant == 'alpineedge' && '-alpine' || '' }}
